# Generated by Django 2.2.5 on 2019-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measure', models.CharField(max_length=10000)),
                ('img_f_path', models.CharField(max_length=200)),
                ('img_s_path', models.CharField(max_length=200)),
                ('img_result_path', models.CharField(max_length=200)),
            ],
        ),
    ]
