# Generated by Django 2.2.5 on 2019-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='img_f_path',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='img_result_path',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='img_s_path',
        ),
        migrations.AddField(
            model_name='subject',
            name='img_f',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='subject',
            name='img_result',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='subject',
            name='img_s',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
