# Generated by Django 2.2.5 on 2019-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191027_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='gender',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='height',
            field=models.FloatField(default=1.5),
        ),
    ]
