# Generated by Django 2.2.5 on 2019-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191027_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img_f',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_result',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_s',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
