# Generated by Django 2.2.5 on 2019-10-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191027_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='img_f',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_result',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_s',
            field=models.ImageField(upload_to='images'),
        ),
    ]
