# Generated by Django 2.2.5 on 2019-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20191029_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img_measure_viz',
            field=models.ImageField(blank=True, upload_to='body_result_viz'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_result',
            field=models.ImageField(blank=True, upload_to='body_result_viz'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_sil_f',
            field=models.ImageField(blank=True, upload_to='body_result_sil'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='img_sil_s',
            field=models.ImageField(blank=True, upload_to='body_result_sil'),
        ),
    ]
