# Generated by Django 2.2.5 on 2019-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20191029_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='measure_gt',
            field=models.CharField(default='{"m_breast_depth": -1, "m_cross_breast": -1, "m_circ_bust": -1, "m_circ_waist": -1, "m_circ_hip": -1, "m_len_front_body": -1, "m_len_half_girth": -1, "m_len_bikini_girth": -1, "m_len_full_girth": -1, "m_circ_neck": -1, "m_circ_upperbust": -1, "m_circ_underbust": -1, "m_circ_highhip": -1, "m_circ_thigh": -1, "m_circ_knee": -1, "m_circ_upperarm": -1, "m_circ_elbow": -1, "m_circ_wrist": -1, "m_shoulder_to_bust": -1, "m_len_upperarm": -1, "m_len_sleeve": -1, "m_len_waist_knee": -1, "m_len_skirt_waist_to_hem": -1}', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='measure_pred',
            field=models.CharField(default='{"m_breast_depth": -1, "m_cross_breast": -1, "m_circ_bust": -1, "m_circ_waist": -1, "m_circ_hip": -1, "m_len_front_body": -1, "m_len_half_girth": -1, "m_len_bikini_girth": -1, "m_len_full_girth": -1, "m_circ_neck": -1, "m_circ_upperbust": -1, "m_circ_underbust": -1, "m_circ_highhip": -1, "m_circ_thigh": -1, "m_circ_knee": -1, "m_circ_upperarm": -1, "m_circ_elbow": -1, "m_circ_wrist": -1, "m_shoulder_to_bust": -1, "m_len_upperarm": -1, "m_len_sleeve": -1, "m_len_waist_knee": -1, "m_len_skirt_waist_to_hem": -1}', max_length=10000),
        ),
    ]
